#!/bin/bash
# Local development setup script for Axon Python package
# This script installs the package in editable mode and helps set up the environment.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
PYTHON_DIR="$ROOT_DIR/axon/python"

echo "========================================================"
echo "    Axon Python Development Setup"
echo "========================================================"

if [[ -z "$CONDA_PREFIX" && -z "$VIRTUAL_ENV" ]]; then
	echo "⚠️  WARNING: You are not inside a Conda or Python virtual environment."
	echo "It is highly recommended to use Conda for local development."
	echo "Press Ctrl+C to abort or Enter to continue..."
	read -r
fi

echo ">> Installing python build dependencies..."
python3 -m pip install -e "${PYTHON_DIR}[dev]"

echo ""
echo ">> Generating local development environment helper (.env)..."
ENV_FILE="$PYTHON_DIR/.env"

if [[ -n "$CONDA_PREFIX" ]]; then
	# We are in a conda environment, we must add the conda lib dir to LD_LIBRARY_PATH
	# to avoid ABI conflicts with the system libstdc++.so.6
	CONDA_LIB_DIR="$CONDA_PREFIX/lib"
	cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/dev_setup.sh
# Source this file before running python tests locally:
# source axon/python/.env
export LD_LIBRARY_PATH="$CONDA_LIB_DIR:\$LD_LIBRARY_PATH"
EOF
	echo "✅ Created $ENV_FILE with Conda library path overrides."
	echo ""
	echo "========================================================"
	echo "    IMPORTANT: ABI Compatibility Warning"
	echo "========================================================"
	echo "Because Bazel uses a modern C++ toolchain, running the built extension"
	echo "against the system's older libstdc++.so.6 will cause segmentation faults."
	echo ""
	echo "To fix this, YOU MUST run the following command in your terminal"
	echo "before running any python scripts directly:"
	echo ""
	echo "    source axon/python/.env"
	echo ""
	echo "Or always execute your scripts like this:"
	echo "    LD_LIBRARY_PATH=\"$CONDA_LIB_DIR:\$LD_LIBRARY_PATH\" python3 ..."
	echo "========================================================"
else
	cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/dev_setup.sh
# Add any required library paths here
EOF
	echo "✅ Created $ENV_FILE"
fi

echo ">> Development setup complete! You can now edit python files in axon/python/axon/ and test them directly."
